HopHub/Models/Beer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace HopHub.Models
{
    public class Beer
    {   
        public int ID { get; set; }
        public string Name { get; set; }

        // ID of beer from BreweryDB API
        public string ReferenceID { get; set; }

        public double? AvgRating { get; set; }
        public IList<Entry> Entries { get; set; }
    }
}

HopHub/Controllers/BeerController.cs
using HopHub.Data;
using HopHub.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using unirest_net.http;

namespace HopHub.Controllers
{
    public class BeerController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IConfiguration configuration;

        public BeerController(ApplicationDbContext dbContext, IConfiguration config)
        {
            context = dbContext;
            configuration = config;
        }

        // Get beer by ID
        public object GetBeer(string id)
        {
            string key = configuration["APIKey"];
            string uri = $"https://api.brewerydb.com/v2/beer/{id}?withBreweries=Y&key={key}";

            HttpResponse<string> singleBeer = Unirest.get(uri).asJson<string>();

            object result = JsonConvert.DeserializeObject<object>(singleBeer.Body);
            return result;
        }

        // GET: /Beer/
        // Displays information of a single beer
        public IActionResult Index(string id)
        {
            bool beerExists = context.Beers.Any(b => b.ReferenceID == id);

            if (beerExists)
            {
                // If beer already in db get beer object by ID
                Beer existingBeer = context.Beers
                    .Single(b => b.ReferenceID == id);

                // Get list of entries of that specific beer that includes a review
                IList<Entry> entries = context.Entries
                    .Where(e => e.Beer.ReferenceID == id && e.Review != null)
                    .Include(e => e.ApplicationUser)
                    .ToList();

                existingBeer.Entries = entries;
                return View(existingBeer);
            }
            return View(new Beer());
        }
    }
}

HopHub/Views/Beer/Add.cshtml
@model AddEntryViewModel
<br />
<br />
<form asp-controller="Beer" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Rating"></label>
        <input class="form-control" asp-for="Rating" />
        <span asp-validation-for="Rating"></span>
    </div>
    <div class="form-group">
        <label asp-for="Review"></label>
        <textarea class="form-control" asp-for="Review" >@Model.Review</textarea>
    </div>
    <div class="form-group">
        <label asp-for="UserComments"></label>
        <textarea class="form-control" asp-for="UserComments">@Model.UserComments</textarea>
    </div>
    <div class="form-group">
        <label asp-for="Location"></label>
        <input class="form-control" asp-for="Location" />
    </div>
    <input asp-for="BeerID" type="hidden" value="@Model.BeerID" />
    <input class="btn btn-default" type="submit" value="Add Entry" />
</form>

HopHub/Views/Beer/Index.cshtml
@model Beer
@section DocumentCSS{ 
    <style>
        .rating > label {
            font-size: 125%;
        }
        h4.review-header{
            color: black;
        }
    </style>
}
@{
    ViewData["Title"] = "Beer Information";
}

<div class="panel panel-default">
    <div class="panel-heading">
        @if (Model.AvgRating > 0)
        {
            <h4 class="panel-title">Average User Rating: @String.Format("{0:0.#}", Model.AvgRating) out of 5</h4>
        }
        else
        {
            <h4 class="panel-title">This beer has not yet been rated.</h4>
        }
    </div>
    <div class="panel-body">
        <div class="media">
            <div class="media-body"></div>
            <div class="media-right"></div>
        </div>
        <div class="info"></div>
    </div>
</div>

@if (Model.AvgRating > 0)
{
    <h4 class="review-header">(@Model.Entries.Count) User Reviews</h4>
    @foreach (var entry in Model.Entries)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Rating: @entry.Rating out of 5</h4>
            </div>
            <div class="panel-body">
                <!-- Rating -->
                <div class="pull-right">
                    <div class="rating">
                        @for (int x = 5; x >= 1; x--)
                        {
                            if (x <= entry.Rating)
                            {
                                <input type="radio" id="@entry.ID+@x" name="rating" value="@entry.ID+@x" />
                                <label class="checked" for="@entry.ID+@x"></label>
                            }
                            else
                            {
                                <input type="radio" id="@entry.ID+@x" name="rating" value="@entry.ID+@x" />
                                <label for="@entry.ID+@x"></label>
                            }
                        }
                    </div>
                </div>
                <!-- Rating -->
                <p>@entry.Review</p>
                <small>Made by @entry.ApplicationUser.UserName on @entry.TimeStamp</small>
            </div>
        </div>
    }
}
else
{
<div class="panel panel-default">
    <div class="panel-body">
        <h4>No Reviews Yet.</h4>
        <p>Be the first to add a review for this beer.</p>
    </div>
</div>
}