HopHub/Controllers/EntryController.cs
using HopHub.Data;
using HopHub.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HopHub.Controllers
{
    public class EntryController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext context;

        public EntryController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            context = dbContext;
            this.userManager = userManager;
        }

        // GET: /Entry/
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                // Get all entries associated with the current user
                string userID = userManager.GetUserId(HttpContext.User);

                IList<Entry> entries = context.Entries
                    .Include(item => item.Beer)
                    .Where(e => e.ApplicationUserID == userID)
                    .ToList();

                return View(entries);
            }
            return Redirect("/Account/Login");
        }

        // GET: /Entry/Add/
        public IActionResult Add(string id, string name)
        {
            // If user is logged in display form to add a beer to their log.
            if (User.Identity.IsAuthenticated)
            {
                AddEntryViewModel addEntryVM = new AddEntryViewModel();
                addEntryVM.BeerID = id;
                addEntryVM.BeerName = name;

                return View(addEntryVM);
            }
            return Redirect("/Account/Login");
        }

        // POST: /Entry/Add/
        [HttpPost]
        public IActionResult Add(AddEntryViewModel addEntryVM)
        {
            if (ModelState.IsValid)
            {
                // If beer doesnt exist already add to database
                bool exists = context.Beers.Any(b => b.ReferenceID == addEntryVM.BeerID);

                if (!exists)
                {
                    Beer newBeer = new Beer
                    {
                        Name = addEntryVM.BeerName,
                        ReferenceID = addEntryVM.BeerID,
                        AvgRating = null
                    };
                    context.Beers.Add(newBeer);
                    context.SaveChanges();
                }

                // Get Beer object by reference ID
                Beer existingBeer = GetBeerById(addEntryVM.BeerID);

                // Get ApplicationUser by ID of current logged in user
                ApplicationUser user = context.Users
                    .Single(u => u.Id == userManager.GetUserId(HttpContext.User));

                // Create new Entry object
                Entry userEntry = new Entry
                {
                    ApplicationUser = user, 
                    Beer = existingBeer,
                    Rating = addEntryVM.Rating,
                    Review = addEntryVM.Review,
                    UserComments = addEntryVM.UserComments,
                    Location = addEntryVM.Location,
                    TimeStamp = DateTime.Now
                };
                
                // Store new user Entry to the database
                context.Entries.Add(userEntry);
                context.SaveChanges();

                // Calculate the average rating for the beer
                SetAverageRating(existingBeer);

                context.Beers.Update(existingBeer);
                context.SaveChanges();

                // Ridirect to user log page.
                return Redirect("/Entry");
            }
            return View(addEntryVM);
        }
        
        // GET: /Entry/Edit/
        public IActionResult Edit(int entryID)
        {
            //Retrieve entry from database by ID
            Entry entryToEdit = GetEntryById(entryID);

            string userIdOfEntry = entryToEdit.ApplicationUserID;
            string currentUserId = userManager.GetUserId(HttpContext.User);

            // Check if the user has access (is the creator) of the object to be edited
            if (User.Identity.IsAuthenticated && userIdOfEntry == currentUserId)
            {
                EditEntryViewModel editEntryVM = EditEntryViewModel.EditEntry(entryToEdit);

                return View(editEntryVM);
            }
            return Redirect("/Entry");
        }
        
        // POST: /Entry/Edit/
        [HttpPost]
        public IActionResult Edit(EditEntryViewModel editEntryVM)
        {
            if (ModelState.IsValid)
            {
                // Update entry details in database
                Entry entryToUpdate = GetEntryById(editEntryVM.ID);

                entryToUpdate.Rating = editEntryVM.Rating;
                entryToUpdate.UserComments = editEntryVM.UserComments;
                entryToUpdate.Review = editEntryVM.Review;
                entryToUpdate.Location = editEntryVM.Location;

                context.Entries.Update(entryToUpdate);
                context.SaveChanges();

                // Update average rating for the beer
                Beer existingBeer = GetBeerById(editEntryVM.BeerID);
                SetAverageRating(existingBeer);

                context.Beers.Update(existingBeer);
                context.SaveChanges();

                return Redirect("/Entry");
            }
            return View(editEntryVM);
        }

        // POST: /Entry/Remove/
        [HttpPost]
        public IActionResult Remove(string id)
        {
            int userId = int.Parse(id);
            Entry entryToRemove = GetEntryById(userId);

            Beer existingBeer = context.Beers
                .Single(b => b.ID == entryToRemove.Beer.ID);

            int beerEntries = context.Entries
                .Where(e => e.BeerID == existingBeer.ID)
                .Count();

            context.Entries.Remove(entryToRemove);
            context.SaveChanges();

            if (beerEntries == 1)
            {
                existingBeer.AvgRating = null;
            }
            else
            {
                SetAverageRating(existingBeer);
                context.Beers.Update(existingBeer);
                context.SaveChanges();
            }

            return Redirect("/Entry");
        }

        #region Helpers

        private void SetAverageRating(Beer beer)
        {
            int sumOfEntries = context.Entries
                    .Where(e => e.BeerID == beer.ID)
                    .Sum(e => e.Rating);

            int numberOfEntries = context.Entries
                    .Where(e => e.BeerID == beer.ID)
                    .Count();

            beer.AvgRating = (double)sumOfEntries / numberOfEntries;
        }

        private Entry GetEntryById(int id)
        {
            Entry entry = context.Entries
                .Include(e => e.Beer)
                .Single(e => e.ID == id);

            return entry;
        }

        private Beer GetBeerById(string id)
        {
            Beer beer = context.Beers
                .Single(b => b.ReferenceID == id);

            return beer;
        }

        #endregion
    }
}

HopHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HopHub</title>
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash|Khand|Lobster+Two|Overpass" rel="stylesheet">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-sandstone.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    <!-- These scripts were moved up from the body -->
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    <!---->
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
        @RenderSection("HeadScripts", required: false)
        @RenderSection("DocumentCSS", required: false)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HopHub</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Entry" asp-action="Index">Entries</a></li>
                </ul>
                @if (ViewData["Title"].ToString() != "Home")
                {
                    // Does not display nav searchbar on main page
                    <form asp-controller="Home" asp-action="Search" method="get" class="navbar-form navbar-left" role="search">
                        <div class="input-group">
                            <input type="search" class="form-control beer" name="beer" placeholder="Search">
                            <span class="input-group-btn">
                                <button class="btn btn-success" type="submit">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                }
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    @if (ViewData["Title"].ToString() == "Home")
    {   
        @RenderBody();
    }
    else
    {
    <div class="container body-content">
        <br />
        <br />
        @RenderBody()
        <br />
        <footer>
            <p class="pull-left">&copy; 2018 - Nico Montanino</p>
            <div class="pull-right">
                <ul class="list-inline">
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Terms</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </footer>
        <br />
    </div>
    }
    <environment include="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <!-- These scripts were moved up up to the header -->
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>